services:
  react-app:
    container_name: frontend
    image: gongcha-front
    restart: unless-stopped
    ports:
      - 5173:5173
    networks:
      - gongcha-network
      
networks:
  gongcha-network:
    external: true

