services:
  spring-boot-app:
    container_name: backend
    image: gongcha-backend
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      REFRESH_EXPIRED: ${JWT_ACCESS_EXPIRED}
      PROD_MYSQL_URI: ${PROD_MYSQL_URI}
      PROD_MYSQL_USERNAME: ${PROD_MYSQL_USERNAME}
      PROD_MYSQL_PASSWORD: ${PROD_MYSQL_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
      NAVER_REDIRECT_URI: ${NAVER_REDIRECT_URI}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}

networks:
  default:
    external:
      name: gongcha-network
